Script started on 2023-04-30 23:51:47-07:00
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ gcc -c -Wall -ansi Image.c -o Image.o
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ gcc -c -Wall -ansi PhotoLab.c -o PhotoLab.o
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ gcc Image.o PhotoLab.o -o PhotoLab
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ ./PhotoLab
wilson.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

wilson.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

wilson.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

wilson.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

wilson.ppm was read successfully!
hmirror.ppm was saved successfully. 
hmirror.jpg was stored for viewing. 
HMirror tested!

wilson.ppm was read successfully!
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

wilson.ppm was read successfully!
xRB.ppm was saved successfully. 
xRB.jpg was stored for viewing. 
ExRB tested!

wilson.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
Crop tested!

AutoTest finished.
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ valgrind --leak-check=full PhotoLa[K[K[K[K[K[K[K./PhootL[K[K[KtoLab
==744004== Memcheck, a memory error detector
==744004== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==744004== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==744004== Command: ./PhotoLab
==744004== 
wilson.ppm was read successfully!
aging.ppm was saved successfully. 
aging.jpg was stored for viewing. 
Aging tested!

wilson.ppm was read successfully!
bw.ppm was saved successfully. 
bw.jpg was stored for viewing. 
Black and White tested!

wilson.ppm was read successfully!
negative.ppm was saved successfully. 
negative.jpg was stored for viewing. 
Negative tested!

wilson.ppm was read successfully!
vflip.ppm was saved successfully. 
vflip.jpg was stored for viewing. 
VFlip tested!

wilson.ppm was read successfully!
hmirror.ppm was saved successfully. 
hmirror.jpg was stored for viewing. 
HMirror tested!

wilson.ppm was read successfully!
==744004== Syscall param write(buf) points to uninitialised byte(s)
==744004==    at 0x4F67BC8: write (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4ED9DAC: _IO_file_write@@GLIBC_2.2.5 (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4ED911E: new_do_write (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4EDAE68: _IO_do_write@@GLIBC_2.2.5 (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4EDB2BE: _IO_file_overflow@@GLIBC_2.2.5 (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4011A1: SaveImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x40228A: AutoTest (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x4023DD: main (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==  Address 0x5551f8f is 15 bytes inside a block of size 4,096 alloc'd
==744004==    at 0x4C37135: malloc (vg_replace_malloc.c:381)
==744004==    by 0x4ECE0FF: _IO_file_doallocate (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4EDC06F: _IO_doallocbuf (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4EDB2D7: _IO_file_overflow@@GLIBC_2.2.5 (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4EDA47E: _IO_file_xsputn@@GLIBC_2.2.5 (in /usr/lib64/libc-2.28.so)
==744004==    by 0x4ECF56B: fwrite (in /usr/lib64/libc-2.28.so)
==744004==    by 0x401105: SaveImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x40228A: AutoTest (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x4023DD: main (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004== 
sharpen.ppm was saved successfully. 
sharpen.jpg was stored for viewing. 
Sharpen tested!

wilson.ppm was read successfully!
xRB.ppm was saved successfully. 
xRB.jpg was stored for viewing. 
ExRB tested!

wilson.ppm was read successfully!
crop.ppm was saved successfully. 
crop.jpg was stored for viewing. 
Crop tested!

AutoTest finished.
==744004== 
==744004== HEAP SUMMARY:
==744004==     in use at exit: 1,264,596 bytes in 12 blocks
==744004==   total heap usage: 77 allocs, 65 frees, 4,334,570 bytes allocated
==744004== 
==744004== 421,532 (32 direct, 421,500 indirect) bytes in 1 blocks are definitely lost in loss record 10 of 12
==744004==    at 0x4C37135: malloc (vg_replace_malloc.c:381)
==744004==    by 0x400BCE: CreateImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x400EB4: LoadImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x40213F: AutoTest (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x4023DD: main (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004== 
==744004== 421,532 (32 direct, 421,500 indirect) bytes in 1 blocks are definitely lost in loss record 11 of 12
==744004==    at 0x4C37135: malloc (vg_replace_malloc.c:381)
==744004==    by 0x400BCE: CreateImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x400EB4: LoadImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x402243: AutoTest (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x4023DD: main (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004== 
==744004== 421,532 (32 direct, 421,500 indirect) bytes in 1 blocks are definitely lost in loss record 12 of 12
==744004==    at 0x4C37135: malloc (vg_replace_malloc.c:381)
==744004==    by 0x400BCE: CreateImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x400EB4: LoadImage (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x402347: AutoTest (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004==    by 0x4023DD: main (in /home/chapman.edu/edilin/ceng231/hw7/PhotoLab)
==744004== 
==744004== LEAK SUMMARY:
==744004==    definitely lost: 96 bytes in 3 blocks
==744004==    indirectly lost: 1,264,500 bytes in 9 blocks
==744004==      possibly lost: 0 bytes in 0 blocks
==744004==    still reachable: 0 bytes in 0 blocks
==744004==         suppressed: 0 bytes in 0 blocks
==744004== 
==744004== Use --track-origins=yes to see where uninitialised values come from
==744004== For lists of detected and suppressed errors, rerun with: -s
==744004== ERROR SUMMARY: 106 errors from 4 contexts (suppressed: 0 from 0)
]0;edilin@WWWSTU-P01:~/ceng231/hw7[edilin@WWWSTU-P01 hw7]$ exit
exit

Script done on 2023-04-30 23:52:53-07:00
